### ISSUE TITLE
Do all the images provided for model computing need to be of same dimension?

### ISSUE THREAD

**Issue by anchitjain1234** [bytefish/facerec#26]
When I run **simple_example.py** with **AT&T database** it runs flawless.
But when I do change the image database and provide it with **different dimension** images it fails and gives me the following error
![Array Dimensions error](https://cloud.githubusercontent.com/assets/4551357/8618005/4bf508b8-2727-11e5-8c0f-bc180fc14d9f.png)

**Comment by bytefish** [comment]
The images need to have the same dimensions for the Eigenfaces and Fisherfaces algorithms. 

The `read_images` method in the script has a parameter (`sz`), which resizes the image to a given size. To resize all images to `120x120` pixels, you can use it like this:

```python
[X,y] = read_images(sys.argv[1], (120,120))
```
