### ISSUE TITLE
Inconsistent Image usage

### ISSUE THREAD

**Issue by simsong** [bytefish/facerec#31]
It appears that facerec has a dependency on PIL Image.

In crop_face.py, there is an `import sys, math, Image` statement.

But in lqp_experiment.py, there is both an `from PIL import Image` and an `import Image`.

It looks like some of the modules assume that Image can be imported as top-level, while other modules try both. 

Should this be consistent?

**Comment by bytefish** [comment]
You have a point. The imports should be consistent, I was very sloppy in the examples. :sweat: I will fix it as soon as I can run the examples at home.

**Comment by simsong** [comment]
Well, I can't even get them to work on my mac because of problems with MacPorts, OpenCV, etc.

I think that everything should run in Python3, but PIL doesn't do Python3....

**Comment by bytefish** [comment]
Probably this helps: 

* [http://python-pillow.github.io](http://python-pillow.github.io)

I can try it with Python3 later today.

**Comment by simsong** [comment]
Python3 is better and it's the future. If you aren't doing crazy sophisticated things with PIL, I would recommend just using OpenCV's image manipulation routines, since you already have an OpenCV dependency.

**Comment by bytefish** [comment]
OpenCV is only neccessary for the examples (if I am not totally mistaken, didn't read my code for quite some time). I didn't want to tie the core framework to OpenCV back then. If I would write such a framework today, I would simply use scikit-learn, which has Image manipulation, classifiers and everything out of the box.

But back to the original problem. 

I have looked at SciPy [ndimage](http://docs.scipy.org/doc/scipy/reference/tutorial/ndimage.html), but it isn't really user-friendly. OpenCV is an alternative, but it is quite large. Matplotlib may also have simple image routines for resizing / reading images.

**Comment by bytefish** [comment]
Code-base is Python3 compatible now.
