### ISSUE TITLE
Distance returned is always 0.

### ISSUE THREAD

**Issue by jseidl** [bytefish/facerec#34]
I've tested both training the videorec demo and my own code with my dataset and they both are giving me false positives. I've put my code to write out the classifier output and distance is shown always as '0.'

The dataset was created by capturing the images and aligning the eyes as in the cited crop_image python script. There are 50 samples in the folder.

I'm acquiring images from a webcam. I've tried placing pictures in front of the webcam. The face detection works and the recognition recognizes any face as mine.

Note: There's only one subject (me). Is this normal to happen? Shouldn't it return something like a huge distance or an unclassified index (like -1)?

Please let me know if you need any additional information

**Comment by jseidl** [comment]
Update: I've trained a second subject from pictures and indeed now gives me the distance. Although whenever I present an unknown face it will predict one of the existing subjects with a similar distance.

**Comment by jseidl** [comment]
After some experimentation I realized that is the nature of the algorithm to always return a match even if the distance is huge when not recognizing properly. Closing this out.

**Comment by bytefish** [comment]
Hi Jan, Thanks for the feedback!
