### ISSUE TITLE
SVM model for classification in classifier.py is not working

### ISSUE THREAD

**Issue by dvigneshwer** [bytefish/facerec#36]
https://github.com/bytefish/facerec/blob/master/py/facerec/classifier.py#L140

svm_model() is not defined in the program.
How to create the svm object for traning the model and use the other class functions for prediction.

**Comment by rockbass2560** [comment]
I have the same doubt, this code line cannot work

![image](https://cloud.githubusercontent.com/assets/2618632/15062074/bb80bfd8-12f9-11e6-9cf6-6be951a17666.png)

**Comment by amsr9** [comment]
I'm facing the same issue!

**Comment by rockbass2560** [comment]
I think this project is incomplete.

**Comment by amsr9** [comment]
Actually Wagner did a great job in developing this project since I have used the simple_example that he attached and it works nicely.  As a newbie in face recognition, I really like it, I've leaned a lot from it.

**Comment by bytefish** [comment]
I think you can simply delete the problematic line and it should work without problems. I can't verify it at the moment, because I don't have access to the develooment environment right now.

Anyway, this is an open source project. Please feel free to make pull requests.

**Comment by rockbass2560** [comment]
I was able to work SVM classifier, you have to use LIBSVM so that you need to download its repository from GitHub and build it. I made a commit for resolving some problems about it. By the way, you have made a great job @bytefish.

**Comment by bytefish** [comment]
Fixed with the latest release, which now uses scikit-learn.
