### ISSUE TITLE
Videofacerec Error

### ISSUE THREAD

**Issue by panagorn** [bytefish/facerec#38]
Hello i tried to run the app with a trained model and i get this error:

File simple_videofacerec.py, line 232, in <module>
    cascade_filename=options.cascade_filename).run()
  File simple_videofacerec.py, line 126, in run
    draw_str(imgout, (x0-20,y0-20), self.model.subject_names[prediction])
  File /home/pi/facerec/py/apps/videofacerec/helper/common.py, line 73, in draw_str
    cv2.putText(dst, s, (x+1, y+1), cv2.FONT_HERSHEY_PLAIN, 1.0, (0, 0, 0), thickness = 2, lineType=cv2.CV_AA)
AttributeError: 'module' object has no attribute 'CV_AA'

**Comment by bytefish** [comment]
Which OpenCV Version did you install? The script was written using OpenCV 2.4.x.

**Comment by berak** [comment]
@panagorn , if you're using opencv3, try `cv2.LINE_AA` instead.

**Comment by panagorn** [comment]
thank you

**Comment by bytefish** [comment]
@berak Thanks for the information. :+1:

**Comment by uzairzia** [comment]
@berak Thank you for the help.

**Comment by flagshipdynamics** [comment]
That worked! Much thanks.

**Comment by Sachin12s19** [comment]
cv2.putText(frame,labelmap[i-1], (int(point[0]),int(point[1])), cv2.FONT_HERSHEY_SIMPLX,2,(255,255,0), 2, cv2.LINE_AA)
      ^
SyntaxError: invalid syntax
I am using openCV version 3.4.0
