### ISSUE TITLE
Face cropping missing in the webservice

### ISSUE THREAD

**Issue by eadmaster** [bytefish/facerec#39]
Is it necessary for the `identify` and the model training methods to have all the images cropped to work properly?

The current implementation does not seem to provide the face detection/cropping feature, but there is some code for that in the `facedet` dir using Opencv.

**Comment by bytefish** [comment]
Issue #50 deals with aligning images using dlib. This should also involve a much simpler pipeline for cropping images. I am thinking about turning the image cropping into a Pipeline element, so it can easily be included in a facerec model.
