### ISSUE TITLE
silly newbie question?

### ISSUE THREAD

**Issue by roryw10** [bytefish/facerec#53]
Hi,

I'm trying to get the example to run and have run into a couple of hurdles. I'm doing my best to follow the tutorial but i am very new to programming. 

As far as i am aware my environment is all set up correctly via anaconda. I have the exact same image set and i am looking to just replicate the code on my own machine before using a different image set and possibly an Eigenfaces instead of fischerfaces. 

I have put a path to the images folder (exactly as in the convention in the tutorial) 

'if len(sys.argv) < 2:
        print("USAGE: facerec_demo.py /Users/me/my-path/facerec/data/images/ [/Users/me/my-path/facerec/data/images/]")
        sys.exit()'

Am i correct in assuming when i run "python simple_example.py" i should see some output / results? Currently i am prompted with "USAGE: facerec_demo.py /Users/me/my-path/..."

Any advice would be much appreciated, i understand this is a very basic question.

**Comment by roryw10** [comment]
sorry solved now, i didnt realise i had to pass the file path into terminal with the file 

I found more documentation that had been put together here 

http://www.bytefish.de/blog/face_recognition_with_opencv2/

Which was super helpful - thanks!

**Comment by bytefish** [comment]
Hey, I just got home. Great to hear, that you have solved it! :+1:

Thanks for letting me know.
