### ISSUE TITLE
Error running simple_example: all the input array dimensions except for the concatenation axis must match exactly

### ISSUE THREAD

**Issue by Raikiree** [bytefish/facerec#54]
this error happens on line 'model.compute(X, y)', wondering why it would raise this. Could you help me?

**Comment by bytefish** [comment]
Yes, some algorithms needs input data with same dimensions. There is a Resize Operator, which can be used in a Pipeline or simpler, you pass a second parameter into the ``read_images(path, sz=None)`` method in the script.

**Comment by Raikiree** [comment]
Thanks!
