### ISSUE TITLE
ValueError: all the input array dimensions except

### ISSUE THREAD

**Issue by nishresthani** [bytefish/facerec#56]
I tried to train binary classification for some images but it gave me following error. 
Any suggestion how to resolve it. 
Thanks 

  File "F:/01_pythonProjects/facerec/faceClassification.py", line 117, in <module>
    model.compute(X, y)
  File "F:\01_pythonProjects\facerec\model.py", line 22, in compute
    features = self.feature.compute(X,y)
  File "F:\01_pythonProjects\facerec\feature.py", line 182, in compute
    Xc = asColumnMatrix(X)
  File "F:\01_pythonProjects\facerec\util.py", line 54, in asColumnMatrix
    mat = np.append(mat, col.reshape(-1,1), axis=1) # same as hstack
  File "F:\program_files\anaconda\lib\site-packages\numpy\lib\function_base.py", line 4575, in append
    return concatenate((arr, values), axis=axis)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by duahimanshu100** [comment]
i am also facing this error, any update?

**Comment by bytefish** [comment]
Some algorithms require the input data to have the same size, so before applying the algorithm the images need to be resized. In the script, there is a method, called ``read_images``, which takes a path and a second parameter for the size.

![image](https://user-images.githubusercontent.com/239373/28543798-4a4bdeb6-70c1-11e7-9ec8-c9025a11db66.png)

Then it can be used like this:

![image](https://user-images.githubusercontent.com/239373/28543838-79d3f272-70c1-11e7-8056-250304865ae7.png)

**Comment by bytefish** [comment]
Let me know, if it fixes the problems.
