### ISSUE TITLE
simple_videofacerec.py syntax error!

### ISSUE THREAD

**Issue by Ru5547** [bytefish/facerec#61]
Very new to python. Using Py 3.6.1 and I get a syntax error on 95 
print "I/O error({0}): {1}".format(errno, strerror)
                              ^
SyntaxError: invalid syntax
Please help

**Comment by bytefish** [comment]
This  is a Python 3 incompability accidentally used in the script.

**Comment by mia-petkovic** [comment]
After applying your changes the error is now in common.py as it should also be rewritten to comply with python 3. Maybe some other files too...

**Comment by bytefish** [comment]
Yes. But that's an OpenCV related problem. I do not have the time to rewrite the example with the latest OpenCV version. So I will add a notice to the README, that the example is Python2 only.
