### ISSUE TITLE
Easy to make memory error when calculate LDA

### ISSUE THREAD

**Issue by wjbKimberly** [bytefish/facerec#64]
This is a great implementation for fisherface. However, since it calculates the Sw value explicitly, memory error is easy to happen. 

For instance, if I have 2000 images in 128*128*3 pixels, and the Sw will have size in(128*128*3)^2. So there is an immediate memory error.

Should you be so kind to help us with this problems.

**Comment by bytefish** [comment]
That's how the algorithm works, so I cannot really help with memory issues.
