### ISSUE TITLE
Does the library support the opencv 3.4.3 

### ISSUE THREAD

**Issue by lzhaoyang** [bytefish/facerec#66]
Hi,I want to know does the library support the opencv 3.4.3  and can it run with python3.6?
Please tell me,Thank you man.

**Comment by bytefish** [comment]
This library actually does run without OpenCV. 

I think there are examples for Face Detection with OpenCV, Do you mean these examples? All examples have only been tested with OpenCV 2.4, so I don't think the examples run with OpenCV 3.4.3. I have no plans to update the library.

Thanks for your interest in the project! 👍

**Comment by bytefish** [comment]
Hey @berak! Great you are still around. 😎

**Comment by lzhaoyang** [comment]
@bytefish Thanks，I see.
