### ISSUE TITLE
a probelm of filereader

### ISSUE THREAD

**Issue by tian-wen** [bytefish/facerec#67]
I have read your blog [here](https://www.bytefish.de/blog/fisherfaces/#eigenfaces) and I want to repeat your experiments. But I can't find the `filereader` module in your repository.Did I miss something? or can you give me the implemention details of the method `FilesystemReader`. Thanks very much.

**Comment by bytefish** [comment]
It was an early first version. There is a folder with the Fisherfaces and Eigenfaces example, which contains a method ``read_images``, which makes the FileSystemReader obsolete. So in short: You don't need it to run the examples.
